<?
$mcart_xls_default_option = [
	'IBLOCK_ID' => 1,
	'PROFILE__QUANTITY_ELEMENTS_IMPORTED_PER_STEP' => 100,
	'PROFILE__ONLY_UPDATE' => 'Y',
	'PROFILE__DEACTIVATE_IF_NEW' => 'Y',
	'PROFILE__DEACTIVATE_IF_QUANTITY_0' => 'Y',
	'PROFILE__DEACTIVATE_IF_PRICE_0' => 'Y',
	'PROFILE__ACTIVATE_IF_QUANTITY_AND_PRICE_NOT_0' => 'Y',
	'PROFILE__END_ROW' => '',
];
