CREATE TABLE IF NOT EXISTS rv_amocrm_status (
  ID int(11) NOT NULL AUTO_INCREMENT,
  SOURCE_TYPE VARCHAR(63) NOT NULL,
  SOURCE_ID VARCHAR(63) NOT NULL,
  EVENT_PARAMS VARCHAR(65535) NOT NULL,
  ADDITIONAL_PARAMS VARCHAR(65535) NOT NULL,
  STATUS CHAR(1) NOT NULL DEFAULT 'N',
  DATE_INSERT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DATE_UPDATE TIMESTAMP,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ENGINE=InnoDB;